// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/arafatazam/godemo/services/hello"
)

// Injectors from injectors.go:

func NewServer() *Server {
	mux := ProvideChi()
	helloHello := hello.ProvideHello()
	server := &Server{
		Mux:     mux,
		helloer: helloHello,
	}
	return server
}
