// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

// Injectors from injectors.go:

func NewServer() *Server {
	mux := ProvideChi()
	server := &Server{
		Mux: mux,
	}
	return server
}
